const fs = require('fs');
const path = require('path');

const template = `// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN

android {
  compileOptions {
      sourceCompatibility JavaVersion.VERSION_17
      targetCompatibility JavaVersion.VERSION_17
  }
}

if (hasProperty('postBuildExtras')) {
  postBuildExtras()
}
`;

const possiblePaths = [
  path.join(__dirname, '..', 'android', 'capacitor.build.gradle'),
  path.join(__dirname, '..', 'android', 'app', 'capacitor.build.gradle')
];

try {
  const filePath = possiblePaths.find(p => fs.existsSync(p)) || possiblePaths[0];
  
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, template, 'utf8');
    console.log(`Created capacitor.build.gradle at: ${filePath}`);
  } else {
    let content = fs.readFileSync(filePath, 'utf8');
    if (content.includes('VERSION_21')) {
      content = content.replace(/JavaVersion\.VERSION_21/g, 'JavaVersion.VERSION_17');
      fs.writeFileSync(filePath, content, 'utf8');
      console.log('Successfully patched capacitor.build.gradle to use Java 17.');
    } else {
      console.log('File already uses correct Java version.');
    }
  }
} catch (error) {
  console.error('Error while patching:', error.message);
  process.exit(1);
} 